language: java
jdk:
- oraclejdk8
before_script:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.10.25" ] || npm install -g npm@1.3.10'
  - npm install -g npm@latest
  - npm --prefix="./src/main/web" install --sixteens-branch=develop --production
#~ script:
  #~ - npm --prefix src/main/web/ test
notifications:
  slack:
    secure: J5FTJJE9MPSLLcpHD/x93ZMwmsnz1ObxwWwgCvH2JGLEdKOkX/x7TbWesX5ni1SkExCiE1CZwdQ2hV5PlQmVvsTGXr9un0+kbKn3btmpsu2ITcoqVuxNUQbRDy0J3jiJhI3GwmbHdkffElVCQ1V6IUj1DPn8xOJbryFX85myego=
#~ deploy:
  #~ provider: heroku
  #~ strategy: api
  #~ api_key:
    #~ secure: fFbMh/6KrdjsSNRgnJqg1b2YHV569lJC8HRMpihP0mhadcw0xYASylG6rP6seMyqCauubQH+1tHw5g5ZmUdVm0jArOnXu8iI648EfUo3H5/TcRcLWyPp5W0D1q4BcXt11iD3c8pT9e9LIaemqjBSc1lHGLrGyOjkTXzWWDKgydg=
  #~ app: onsbeta
  #~ on:
    #~ repo: ONSdigital/babbage
git:
  submodules: false


